# Generated by Django 3.1.7 on 2021-11-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0003_auto_20211112_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume',
            field=models.CharField(blank=True, max_length=255, verbose_name='Максимальный объем sd карты'),
        ),
    ]
