# Generated by Django 3.1.7 on 2021-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0004_auto_20211112_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Итоговая цена'),
        ),
    ]
