# Generated by Django 3.1.7 on 2021-11-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0012_auto_20211119_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='описание товара')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name=' Ширина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('volume_of_the_refrigerating_chamber', models.CharField(max_length=255, verbose_name='Объем холодильной камеры')),
                ('freezer_capacity', models.CharField(max_length=255, verbose_name='Объем морозильной камеры')),
                ('no_frost', models.BooleanField(default=True, verbose_name='Система No Frost')),
                ('shelves_refrigerating', models.CharField(blank=True, max_length=255, verbose_name='Полок в холодильной камере')),
                ('shelves_freezer', models.CharField(max_length=255, verbose_name='Полок на двери хол. камеры')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digits.category', verbose_name='категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
