# Generated by Django 3.1.7 on 2021-11-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0013_fridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='no_frost',
            field=models.CharField(max_length=255, verbose_name='Система No Frost'),
        ),
    ]
