# Generated by Django 3.1.7 on 2021-11-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0014_auto_20211127_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='описание товара')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name=' Ширина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('burners', models.CharField(max_length=255, verbose_name='Количество конфорок')),
                ('protection_from_children', models.CharField(max_length=255, verbose_name='Защита от детей')),
                ('body', models.CharField(max_length=255, verbose_name='Материал варочной поверхности')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digits.category', verbose_name='категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
